### ISSUE TITLE
Gene tree or species tree input?

### ISSUE THREAD

**Issue by keren210** [CarineRey/pcoc#18]
Hi there,

I was wondering whether it's correct to use a gene tree instead of a species tree as input for PCOC?

This issue is a bit confusing to me as I am dealing with some genes under high selection pressure, so the gene tree doesn't really resemble the species tree. I used the former in my analysis, and it creates a bit of a messy situation when trying to flag branches while testing for convergent scenarios.

Thanks in advance for your time, and let me know if you need any more information!

**Comment by CarineRey** [comment]
Hi,
PCOC needs the species tree. Indeed you have to annotate the species tree with the convergent events. In a gene tree, (convergent) evolution can mix branches.

**Comment by keren210** [comment]
Great, thank you very much for clarifying this!
