### ISSUE TITLE
Small tool to convert from leaf labels to node number

### ISSUE THREAD

**Issue by melop** [CarineRey/pcoc#2]
I am trying to run PCOC on a large number of alignments. I thought it would be useful to have a tool that automatically returns the MRCA branches given a set of leaf names, so that people don't have to visually inspect the output of pcoc_num_tree.py.

The attached script first matches the provided taxa list with the tree, takes only the taxa that are present, and return all node numbers for the clade. The MRCA node of each event is put as the first node.

Usage:
usage: pcoc_taxa2nodenum.py -t TREE -L TIPLABELS

TIPLABELS is a comma separated list of leaf names, each event is separated by "/".

E.g. Apple,Orange,Pear/Pine,Gingko,Melon

[pcoc_taxa2nodenum.py.zip](https://github.com/CarineRey/pcoc/files/2201712/pcoc_taxa2nodenum.py.zip)

**Comment by CarineRey** [comment]
It is good idea,  I will add a section in the wiki.
Thank you.

**Comment by yuzhenpeng** [comment]
Dear Ray，

I'm sorry to bother you. I feel a little confused about the input file. Where can I get the gene tree with values for branch lengths? Could you please tell me what software can do this? PAML or MEGA?

**Comment by melop** [comment]
@yuzhenpeng 

I inferred gene trees with RAxML from the nucleotide alignment. PhyML was used in their paper, but it's very slow, that's why I used RAxML "-f a" option.

Then you need to root the tree because RAxML produces unrooted trees (maybe it's possible to select outgroups, but I haven't tried).

Ray

**Comment by yuzhenpeng** [comment]
@melop 

Thank you very much for your help.

I would like to continue to ask one question. If I have a large number of genes, does it mean that there should be the same number of gene trees or just one species tree is enough?

**Comment by melop** [comment]
@yuzhenpeng 
I inferred gene trees for each gene alignment. Due to incomplete lineage sorting or hybridization, the gene trees may not agree with the species tree. The branch lengths will also differ from gene to gene. It's better I think to infer trees individually. 

Ray

**Comment by yuzhenpeng** [comment]
@melop 

Now I am not confused.
Thank you.

**Comment by Ptero64** [comment]
Hello @CarineRey and @melop 

I will be interested to run pcoc on a large number of loci. I have followed the tutorial but I still have few questions. 

For the trees input, it has to be a inferred gene tree from the aa alg or it could be from the nucleo alg? Or do you used a species tree and prune taxa not present in each alignment (pcoc #4 issue)?

I came also to the same problem as @melop to avoid to open each of the pcoc_num_tree.py output for each genes to get the string labels. I tried your script pcoc_taxa2nodenum.py. It work well except when one of the leaf name is unique, or labels not come as monophyletic for a specific gene tree. I haven't tried yet, but I suppose that it doesn't like missing data too?
My labels look like: bats1,bats2,bats4/bats5/bats6,bats7/bats8/bats9,bats10,bats11

Is there another option to loop to get the string for each gene trees?

I thank you in advance for the advices and help,
Best
Nicolas

**Comment by CarineRey** [comment]
Hello,
For the input trees, you should use a species tree inferred from all your loci (or another if you have another).

**Comment by Ptero64** [comment]
Hello Carine,
Thanks for very for your help.
Using the trim option I was able to run it in one script without problem, thanks.
Best,
Nicolas

**Comment by Ptero64** [comment]
Hello Carine,
I have another question about how are take into account missing data when running pcoc. 
My loci have some missing data which were originally coded by ? in my alignments. I recoded them as X. But I got several results with pp>0.8 for (mostly) the submodel PC selecting positions for which several of my convergent species have missing data (X). 

Is it better to code missing data differently (by -) or to remove thoses positions?

Thank you.
Best,
Nicolas

**Comment by CarineRey** [comment]
Hello Nicolas,

"-" and "X" are interpreted of the same way in pcoc. To discard sites with a lot of missing data you can use the  `--max_gap_allowed` and/or `--max_gap_allowed_in_conv_leaves`  options.

```--max_gap_allowed MAX_GAP_ALLOWED
                        max gaps allowed to take into account a site (in %),
                        must be between 0 and 100 (default:5%)
  --max_gap_allowed_in_conv_leaves MAX_GAP_ALLOWED_IN_CONV_LEAVES
                        max gaps allowed in convergent leaves to take into
                        account a site (in %), must be between 0 and 100
                        (default:5%)
```

Best,
Carine

**Comment by Ptero64** [comment]
Hello Carine,
Great, thank you very much for the help.
Best,
Nicolas
