### ISSUE TITLE
More complex convergent scenarios

### ISSUE THREAD

**Issue by NatJWalker-Hale** [CarineRey/pcoc#23]
Hi @CarineRey,

I just wanted to ask about how PCOC might handle a convergent scenario where some but not all of the nodes descending the transition node are in the convergent foreground set?

Let's say we have an example where the convergent transition is followed by a loss/reversal of convergent activity in a subset of descendant tips: `/TransitionNode,Some,But,Not,All,Descendants`, etc. How would PCOC handle this scenario specification?

From tests, I know that practically running said scenario is no problem. From looking at the tree topologies, I see that the tree_conv.nhx merely groups the subclade of the transition node which is annotated as retaining the activity with the rest of the convergent clades, which is the desired outcome and suggests that the PC submodel will calculate correctly. However, will the OC and PCOC models account for transition along the specified transition node, or will that cause an error?

Thanks so much in advance for your help,

Best,

Nathanael

**Comment by lgueguen** [comment]
Hi Nathanael,

about the first point, from the modeling part, you can set the background model on the branches that lead to your "ancestral" activity, and in Bio++ it is not a problem. 

About the second point, as long as we look for  a "forced" substitution on the transition branch, so I think the OC & PCOC will work. But I am not sure I have really understood your question.

Cheers,
Laurent

**Comment by NatJWalker-Hale** [comment]
Hi @lgueguen, 

Fantastic, thanks so much for the help and clarification. I was mostly concerned that the model would 'force' the substitution to occur along the specified transition branch, and not for example along the MRCA of the tips labelled as the foreground condition, so you've clarified perfectly.

Cheers,
Nathanael
