### ISSUE TITLE
Question about pcoc usage

### ISSUE THREAD

**Issue by Vizueta** [CarineRey/pcoc#6]
Hello,

I write these issue as I am having some doubts and errors using pcoc. Basically, I would like to know if it makes sense to apply your method to a phylogenetic tree with only 5 species, in which only two branches are candidates to accumulate convergent changes (two events, see tree below)

(1,((2,3), (4.5))); # branches 2 and 5 are the candidates.

I ran your program with this configuration in 22 candidate genes from our previous genomic analysis and I got some sites with PP>0.95, but I am not sure if they are false positives. 

In fact, I tried running a simulation study to answer this question. I used this command:

$CMD_PCOC_DOCKER pcoc_sim.py -t protein_aln/species_tree/ -o pcoc_sim/sptree_pcoc_det_sim -m "2/5" -c 2 -n_sc 1 --pcoc -nb_sampled_couple 10 -n_sites 100

Nevertheless, I got an error (see attached the output folder) and I don't know how to proceed. 
I used "/" to separate the scenarios, considering them as independent in each of these two branches, but I am not sure if I should use the comma instead, because results are not what I expect.
[OG6704_pcoc_det_sim_error.zip](https://github.com/CarineRey/pcoc/files/2345682/OG6704_pcoc_det_sim_error.zip)

I would greatly appreciate your help.
Sincerely,
Joel Vizueta.

**Comment by CarineRey** [comment]
Hello,

In fact it was a bug, I fixed it. Thank you for the report. Don't forget to do a `docker pull carinerey/pcoc`

Sincerely,
Carine Rey
